services:
  # Main Application
  app:
    build: .
    container_name: gemini_app
    restart: always
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      # Database Connection
      # Format: postgresql://USER:PASSWORD@HOST:PORT/DB_NAME?schema=public
      DATABASE_URL: "postgresql://postgres:917457@postgres:5432/clicloud?schema=public"
      
      # Redis Connection
      # Format: redis://:PASSWORD@HOST:PORT
      REDIS_URL: "redis://:917457@redis:6379"
      
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true